# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Check Your Bias
email: checkyourbias@u.washington.edu
email_archives: http://mailman11.u.washington.edu/pipermail/checkyourbias/
description: > # this means to ignore newlines until "baseurl:"
  Project information and updates

baseurl: "/CheckYourBias" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github_username: aaronnech
github_project: CheckYourBias

# Build settings
markdown: kramdown
paginate: 5